# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PartyPoint' do
  pod 'SnapKit', '~> 5.6.0'
  pod 'lottie-ios'	
  pod 'SwiftSoup'
  pod 'Kingfisher', '~> 7.0'
  pod 'R.swift'
end
